from portfolio.settings.common import *
import os

DEBUG = False

SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

ALLOWED_HOSTS = os.environ['DJANGO_ALLOWED_HOSTS'].split(',')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASSWORD'],
        'HOST': os.environ['DB_HOST'],
        'PORT': os.environ['DB_PORT'],
    }
}

CORS_ALLOWED_ORIGINS = os.environ['DJANGO_CORS_ALLOWED_ORIGINS'].split(',')

GOOGLE_CLIENT_SECRET_FILEPATH = os.environ['GOOGLE_CLIENT_SECRET_FILEPATH']
GOOGLE_CLIENT_TOKEN_FOLDER = os.environ['GOOGLE_CLIENT_TOKEN_FOLDER']
GOOGLE_CLIENT_FLOW_REDIRECT_URI = os.environ['GOOGLE_CLIENT_FLOW_REDIRECT_URI']

EMAIL_RECIPIENT_ADDRESS_LIST = os.environ['EMAIL_RECIPIENT_ADDRESS_LIST'].split(',')
EMAIL_SENDER_ADDRESS = os.environ['EMAIL_SENDER_ADDRESS']

CELERY_BROKER_URL = os.environ["REDIS_URL"]
CELERY_RESULT_BACKEND = os.environ["REDIS_URL"]

CONTACT_FORM_NAME_MAXLENGTH = os.environ['CONTACT_FORM_NAME_MAXLENGTH']
CONTACT_FORM_COMPANY_MAXLENGTH = os.environ['CONTACT_FORM_COMPANY_MAXLENGTH']
CONTACT_FORM_EMAIL_MAXLENGTH = os.environ['CONTACT_FORM_EMAIL_MAXLENGTH']
CONTACT_FORM_EMAIL_REGEX = os.environ['CONTACT_FORM_EMAIL_REGEX']
CONTACT_FORM_MESSAGE_CONTENT_MAXLENGTH = os.environ['CONTACT_FORM_MESSAGE_CONTENT_MAXLENGTH']
CONTACT_FORM_MESSAGE_CONTENT_MINLENGTH = os.environ['CONTACT_FORM_MESSAGE_CONTENT_MINLENGTH']

