# Generated by Django 3.2.12 on 2022-03-25 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactForm', '0008_auto_20220325_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
