# Generated by Django 3.2.12 on 2022-03-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactForm', '0009_alter_message_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(check=models.Q(('name__length__gte', 1)), name='CHK_ContactForm_Message_Name_Length_GTE_1'),
        ),
    ]
