# Generated by Django 3.2.12 on 2022-03-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactForm', '0010_message_chk_contactform_message_name_length_gte_1'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(check=models.Q(('name__length__lte', 120)), name='CHK_ContactForm_Message_Name_Length_LTE_120'),
        ),
    ]
